### ISSUE TITLE
Hi dear, how can I replace your camera video with mine, and compute out my results?

### ISSUE THREAD

**Issue by scofield7419** [santhosh-kumar/ContextualObjectSearchRetrieval#1]
Dear sir, I noticed your work resently, and I wanna replace your camera video with mine to have my own results.
Here I have several videos witch are shoted at the same one scenario but in different angles.
I've already read your codes and still got some puzzles:
1. what's the colordriftpattern?
2. what's the tracklets?
3.and more...

Thx! and looking forward to your reply.

**Comment by santhosh-kumar** [comment]
This code implements the paper: http://ieeexplore.ieee.org/document/7312467/?reload=true

As mentioned in the instructions, you can download the sample data folder from: https://www.dropbox.com/s/dp558f6rzcd3yke/data.zip?dl=0 and start running the code.
